language: java
sudo: false
install: true

jdk:
  - oraclejdk8

script:
  - mvn verify -B -e -V

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: poypost@gmail.com

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "${GH_NAME}"
  - git config --local user.email "${GH_EMAIL}"
  - git tag "sonar-l10n-zh-tw-plugin-7.7.${TRAVIS_BUILD_NUMBER}"
  - mv target/sonar-l10n-zh-tw-plugin-7.7.jar target/sonar-l10n-zh-tw-plugin-7.7.${TRAVIS_BUILD_NUMBER}.jar

deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file: "target/sonar-l10n-zh-tw-plugin-7.7.${TRAVIS_BUILD_NUMBER}.jar"
  skip_cleanup: true
